name 'groupinstall'
maintainer 'Strahil Nikolov'
maintainer_email 'hunter86_bg@yahoo.com'
license 'BSD-3-Clause'
description 'Installs/Configures packages via yum/dnf groups'
version '1.1.0'

supports 'redhat', '>= 5.0'
supports 'centos', '>= 5.0'
supports 'fedora', '>= 19.0'
supports 'fedora', '< 22.0'
